# -*- coding: utf-8 -*-
"""lending_ai_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ur0C-70kgZhCkpCmJqNwryvKVsL-Eid6

# 🏦 Lending AI — Complete Fine-Tuning Pipeline

**Model:** `meta-llama/Llama-3.2-3B-Instruct` + QLoRA  |  **GPU:** T4 (15 GB)

| Step | What happens |
|------|--------------|
| 1 | Install packages + verify GPU |
| 2 | Clone repo from GitHub |
| 3 | Upload raw dataset → full data preparation pipeline |
| 4 | HuggingFace login |
| 5 | Fine-tune Llama-3.2-3B with QLoRA (~20 min) |
| 6 | Evaluate: base model vs fine-tuned (Accuracy, F1, ROUGE) |
| 7 | 3 side-by-side demo scenarios |
| 8 | Download all outputs |

> **Runtime → Run all** — cells run sequentially, nothing to configure.

## ⚙️ Step 1 — Environment Setup
"""

import subprocess, sys
result = subprocess.run(['nvidia-smi','--query-gpu=name,memory.total','--format=csv,noheader'],
                        capture_output=True, text=True)
if result.returncode == 0:
    print('✅ GPU:', result.stdout.strip())
else:
    print('❌ No GPU — go to Runtime → Change runtime type → T4 GPU')
    sys.exit()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers>=4.40.0 peft>=0.10.0 trl>=0.8.6 bitsandbytes>=0.43.0 \
#              accelerate>=0.27.0 datasets>=2.18.0 evaluate>=0.4.1 rouge-score \
#              scikit-learn openpyxl scipy pyyaml tqdm
# print('done')

import torch, transformers, peft, trl
print(f'PyTorch {torch.__version__} | Transformers {transformers.__version__}')
print(f'PEFT {peft.__version__} | TRL {trl.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')
print('✅ All packages ready')

"""## 📂 Step 2 — Clone Repository"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/anmolvarshney77/SLM-Lending-and-Credit lending-ai-slm
# %cd lending-ai-slm
!ls

"""## 🤗 Step 3 — HuggingFace Login
Token is pre-filled — just run the cell.
"""

from huggingface_hub import login
login(token='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', add_to_git_credential=False)
print('✅ Logged in to HuggingFace')

"""## 📊 Step 4 — Upload Dataset & Run Data Pipeline
Upload **`Lending_Loan_Portfolio_1000_Raw.xlsx`** when the picker appears.
"""

import os, shutil
from google.colab import files

os.makedirs('data/raw', exist_ok=True)
print('📁 Select Lending_Loan_Portfolio_1000_Raw.xlsx ...')
uploaded = files.upload()
for fname in uploaded:
    shutil.move(fname, f'data/raw/{fname}')
    print(f'✅ Saved → data/raw/{fname}')

import sys
sys.path.insert(0, 'src')
from data_prep import run_pipeline

import os

# Rename the uploaded file to its original name if it was saved with a suffix
expected_path = 'data/raw/Lending_Loan_Portfolio_1000_Raw.xlsx'
alternate_path = 'data/raw/Lending_Loan_Portfolio_1000_Raw (1).xlsx'

if os.path.exists(alternate_path) and not os.path.exists(expected_path):
    os.rename(alternate_path, expected_path)
    print(f'✅ Renamed "{os.path.basename(alternate_path)}" to "{os.path.basename(expected_path)}"')

df = run_pipeline()
print('\n✅ Data pipeline complete')

import json

# Split sizes
for split in ['train', 'val', 'test']:
    with open(f'data/processed/{split}.jsonl') as f:
        n = sum(1 for _ in f)
    print(f'{split:6s}: {n} examples  ({n//3} records × 3 tasks)')

print()
print('Risk Label distribution:')
print(df['RISK_LABEL'].value_counts().to_string())
print()
print('Approval Label distribution:')
print(df['APPROVAL_LABEL'].value_counts().to_string())

# Preview one example of each task type
with open('data/processed/train.jsonl') as f:
    examples = [json.loads(l) for l in f]

task_keywords = {
    'RISK':     ['classify','risk category','risk assessment'],
    'APPROVAL': ['approval','approve','should this loan'],
    'SUMMARY':  ['summarise','summarize','summary','narrative'],
}
shown = set()
for ex in examples:
    user = ex['messages'][1]['content'].lower()
    for task, kws in task_keywords.items():
        if task not in shown and any(k in user for k in kws):
            shown.add(task)
            print(f'{"-"*65}')
            print(f'TASK: {task}')
            print(f'{"-"*65}')
            print('USER (first 300 chars):')
            print(ex['messages'][1]['content'][:300])
            print()
            print('ASSISTANT:')
            print(ex['messages'][2]['content'][:500])
            print()
    if len(shown) == 3:
        break

"""## 🔥 Step 5 — Load Llama-3.2-3B-Instruct (4-bit QLoRA)

**Why QLoRA over full fine-tuning?**
- Full fine-tune: ~48 GB VRAM, hours of training
- QLoRA: freezes base in 4-bit NF4, trains only adapter matrices → **~6.5 GB VRAM, ~20 min**
- Preserves language understanding, injects domain knowledge

**LoRA config rationale:**
- `r=16`: enough capacity without overfitting 2,400 examples
- `alpha=32`: standard 2× scaling → stable gradients at init
- target all 4 attention projections: maximises domain transfer surface
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

MODEL_NAME    = 'meta-llama/Llama-3.2-3B-Instruct'
compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
)

print(f'Loading {MODEL_NAME}...')
print('First run downloads ~1.5 GB — takes 2-3 min')

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map='auto',
    trust_remote_code=True,
    torch_dtype=compute_dtype,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
tokenizer.pad_token    = tokenizer.eos_token
tokenizer.padding_side = 'right'

print(f'\n✅ Model loaded on {next(base_model.parameters()).device}')
print(f'   dtype: {compute_dtype}')

base_model = prepare_model_for_kbit_training(base_model, use_gradient_checkpointing=True)
base_model.config.use_cache = False

lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05,
    bias='none', task_type='CAUSAL_LM',
    target_modules=['q_proj','k_proj','v_proj','o_proj'],
)
model = get_peft_model(base_model, lora_config)

trainable, total = model.get_nb_trainable_parameters()
print(f'Trainable params : {trainable:,}  ({100*trainable/total:.4f}% of {total:,} total)')
print('Base weights FROZEN — only LoRA adapters will update ✅')

"""## 🚂 Step 6 — Fine-Tune with SFTTrainer
Expected: **15–25 min** on T4.  
Watch `eval_loss` decreasing — that's the model learning domain concepts.
"""

import time, os, json
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer

def load_jsonl(path):
    records = []
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return Dataset.from_list(records)

train_ds = load_jsonl('data/processed/train.jsonl')

# --- MAXIMUM SPEED OPTIMIZATION (Sub-10 Minute Target) ---
# Reducing data to ensure fast preprocessing and startup
train_ds = train_ds.select(range(min(1200, len(train_ds))))
print(f'Train (Fast-Mode): {len(train_ds)} examples')

use_bf16 = torch.cuda.is_bf16_supported()
os.makedirs('outputs/adapter', exist_ok=True)

training_args = TrainingArguments(
    output_dir='outputs/adapter',
    max_steps=30,                  # Hard cutoff for ~5-8 mins run
    per_device_train_batch_size=8,
    gradient_accumulation_steps=1,
    gradient_checkpointing=False,
    learning_rate=5e-4,
    lr_scheduler_type='linear',
    warmup_steps=5,
    weight_decay=0.01,
    fp16=not use_bf16,
    bf16=use_bf16,
    eval_strategy='no',            # Corrected parameter name
    save_strategy='no',
    logging_steps=5,
    report_to='none',
    seed=42,
)

def formatting_func(example):
    return tokenizer.apply_chat_template(
        example['messages'],
        tokenize=False,
        add_generation_prompt=False
    )

# Stable SFTTrainer initialization
trainer = SFTTrainer(
    model=base_model,
    train_dataset=train_ds,
    formatting_func=formatting_func,
    args=training_args,
    peft_config=lora_config,
)

print(f'Fast Mode Enabled | Target Steps: 30')
print('Starting 10-minute sprint training...')
t0 = time.time()
train_result = trainer.train()
elapsed = time.time() - t0

print(f'\n✅ Done in {elapsed/60:.1f} min  |  Final loss: {train_result.metrics["train_loss"]:.4f}')

import matplotlib.pyplot as plt

log = trainer.state.log_history
ts  = [x['step'] for x in log if 'loss' in x and 'eval_loss' not in x]
tl  = [x['loss'] for x in log if 'loss' in x and 'eval_loss' not in x]
es  = [x['step'] for x in log if 'eval_loss' in x]
el  = [x['eval_loss'] for x in log if 'eval_loss' in x]

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(ts, tl, label='Train Loss',      alpha=0.7, color='#3B6EFF')
ax.plot(es, el, label='Validation Loss', alpha=0.9, color='#F59E0B',
        linewidth=2, marker='o', markersize=5)
ax.set_xlabel('Steps'); ax.set_ylabel('Loss')
ax.set_title('QLoRA Fine-Tuning — Loss Curves')
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
os.makedirs('outputs', exist_ok=True)
plt.savefig('outputs/training_loss.png', dpi=150)
plt.show()

import json, os

# Check if training actually completed successfully
if 'train_result' in globals():
    trainer.model.save_pretrained('outputs/adapter')
    tokenizer.save_pretrained('outputs/adapter')

    metrics = dict(train_result.metrics)
    metrics['elapsed_minutes'] = elapsed / 60
    metrics['model_name'] = MODEL_NAME

    os.makedirs('outputs', exist_ok=True)
    with open('outputs/training_metrics.json','w') as f:
        json.dump(metrics, f, indent=2, default=str)

    print('✅ Adapter and metrics saved to outputs/adapter/')
    print('Files:', os.listdir('outputs/adapter'))
else:
    print('❌ Error: Training has not completed yet. Please ensure the training cell (BzSsGQqhKKrs) finishes successfully before running this.')

"""## 📈 Step 7 — Evaluation: Base Model vs Fine-Tuned

We toggle the adapter on/off — one model object, clean comparison on the same test set.

**Metrics:**
- Classification: Accuracy, F1 Macro, Per-class Recall
- Generation: ROUGE-1/2/L + Domain Term Recall (% of lending terms used correctly)
- Business: High-Risk borrower recall (most critical — maps directly to defaulter detection)
"""

import re, numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score, classification_report

DOMAIN_TERMS = [
    'bureau','dpd','foir','delinquency','delinquent','emi',
    'credit utilization','collection bucket','outstanding','write-off',
    'default','sanction','repayment','overdue','risk',
]

def detect_task(msg):
    m = msg.lower()
    if any(w in m for w in ['summarise','summarize','summary','narrative']): return 'summary'
    if any(w in m for w in ['classify','risk category','risk assessment']):  return 'risk'
    if any(w in m for w in ['approval','approve','should this loan']):        return 'approval'
    return 'unknown'

def extract_label(text, task):
    if task == 'risk':
        if re.search(r'high risk',   text, re.I): return 'High Risk'
        if re.search(r'medium risk', text, re.I): return 'Medium Risk'
        if re.search(r'low risk',    text, re.I): return 'Low Risk'
        return 'Unknown'
    if task == 'approval':
        if re.search(r'approve with conditions', text, re.I): return 'Approve with Conditions'
        if re.search(r'\breject\b',  text, re.I): return 'Reject'
        if re.search(r'\bapprove\b', text, re.I): return 'Approve'
        return 'Unknown'
    return text

def domain_recall(text):
    t = text.lower()
    return sum(1 for w in DOMAIN_TERMS if w in t) / len(DOMAIN_TERMS)

@torch.no_grad()
def infer(mdl, msgs, max_new=300):
    prompt = tokenizer.apply_chat_template(
        msgs[:-1], tokenize=False, add_generation_prompt=True)
    inp = tokenizer(prompt, return_tensors='pt', truncation=True, max_length=512)
    inp = {k: v.to(mdl.device) for k,v in inp.items()}
    out = mdl.generate(**inp, max_new_tokens=max_new, do_sample=False,
                        pad_token_id=tokenizer.pad_token_id)
    new = out[0][inp['input_ids'].shape[1]:]
    return tokenizer.decode(new, skip_special_tokens=True).strip()

with open('data/processed/test.jsonl') as f:
    test_data = [json.loads(l) for l in f]
print(f'Test examples: {len(test_data)}')
print('✅ Eval helpers ready')

def run_eval(adapter_on, label, cap=33):
    if adapter_on:
        model.enable_adapter_layers()
    else:
        model.disable_adapter_layers()

    r = {'risk':     {'y_true':[], 'y_pred':[], 'dr':[]},
         'approval': {'y_true':[], 'y_pred':[]},
         'summary':  {'refs':[], 'preds':[], 'dr':[]}}
    cnt = {'risk':0,'approval':0,'summary':0}

    for ex in tqdm(test_data, desc=label):
        msgs = ex['messages']
        task = detect_task(msgs[1]['content'])
        if task == 'unknown' or cnt.get(task,0) >= cap:
            continue
        ref  = msgs[2]['content']
        pred = infer(model, msgs)
        if task in ('risk','approval'):
            r[task]['y_true'].append(extract_label(ref,  task))
            r[task]['y_pred'].append(extract_label(pred, task))
        if task == 'risk':
            r['risk']['dr'].append(domain_recall(pred))
        if task == 'summary':
            r['summary']['refs'].append(ref)
            r['summary']['preds'].append(pred)
            r['summary']['dr'].append(domain_recall(pred))
        cnt[task] += 1

    print(f'{label}: {cnt}')
    return r

print('Evaluating BASE model (adapter OFF)...')
base_res = run_eval(False, 'Base Model')

print('\nEvaluating FINE-TUNED model (adapter ON)...')
ft_res = run_eval(True, 'Fine-Tuned')

print('\n✅ Inference complete')

import pandas as pd

def cls_metrics(y_true, y_pred, labels):
    acc = accuracy_score(y_true, y_pred)
    f1  = f1_score(y_true, y_pred, average='macro', labels=labels, zero_division=0)
    rep = classification_report(y_true, y_pred, labels=labels, output_dict=True, zero_division=0)
    return acc, f1, rep

RISK_LABELS = ['Low Risk', 'Medium Risk', 'High Risk']
APPR_LABELS = ['Approve', 'Approve with Conditions', 'Reject']

ba, bf, br  = cls_metrics(base_res['risk']['y_true'],     base_res['risk']['y_pred'],     RISK_LABELS)
fa, ff, fr  = cls_metrics(ft_res['risk']['y_true'],       ft_res['risk']['y_pred'],       RISK_LABELS)
baa,baf,bar = cls_metrics(base_res['approval']['y_true'], base_res['approval']['y_pred'], APPR_LABELS)
faa,faf,far = cls_metrics(ft_res['approval']['y_true'],   ft_res['approval']['y_pred'],   APPR_LABELS)

sep = '='*60
print(sep)
print('  CREDIT RISK CLASSIFICATION')
print(sep)
rows = []
for cls in RISK_LABELS:
    b = br.get(cls,{}); f = fr.get(cls,{})
    rows.append({'Class': cls,
        'Base F1':f"{b.get('f1-score',0):.3f}", 'FT F1':f"{f.get('f1-score',0):.3f}",
        'Base Recall':f"{b.get('recall',0):.3f}", 'FT Recall':f"{f.get('recall',0):.3f}"
    })
print(pd.DataFrame(rows).to_string(index=False))
print(f'\nAccuracy : Base {ba:.1%}  →  FT {fa:.1%}  (Δ {fa-ba:+.1%})')
print(f'F1 Macro : Base {bf:.4f}  →  FT {ff:.4f}  (Δ {ff-bf:+.4f})')

print()
print(sep)
print('  LOAN APPROVAL RECOMMENDATION')
print(sep)
rows2 = []
for cls in APPR_LABELS:
    b = bar.get(cls,{}); f = far.get(cls,{})
    rows2.append({'Class': cls,
        'Base F1':f"{b.get('f1-score',0):.3f}", 'FT F1':f"{f.get('f1-score',0):.3f}"
    })
print(pd.DataFrame(rows2).to_string(index=False))
print(f'\nAccuracy : Base {baa:.1%}  →  FT {faa:.1%}  (Δ {faa-baa:+.1%})')
print(f'F1 Macro : Base {baf:.4f}  →  FT {faf:.4f}  (Δ {faf-baf:+.4f})')

# Business impact: High Risk recall
y_true = base_res['risk']['y_true']
b_pred = base_res['risk']['y_pred']
f_pred = ft_res['risk']['y_pred']

n_high  = sum(t == 'High Risk' for t in y_true)
b_tp    = sum(p == 'High Risk' and t == 'High Risk' for p,t in zip(b_pred, y_true))
f_tp    = sum(p == 'High Risk' and t == 'High Risk' for p,t in zip(f_pred, y_true))
b_rec   = b_tp / n_high if n_high else 0
f_rec   = f_tp / n_high if n_high else 0

b_dr    = np.mean(base_res['risk']['dr']) if base_res['risk']['dr'] else 0
f_dr    = np.mean(ft_res['risk']['dr'])   if ft_res['risk']['dr']   else 0

b_sdr   = np.mean(base_res['summary']['dr']) if base_res['summary']['dr'] else 0
f_sdr   = np.mean(ft_res['summary']['dr'])   if ft_res['summary']['dr']   else 0

print('='*60)
print('  BUSINESS IMPACT')
print('='*60)
print(f'High Risk borrowers in test set : {n_high}')
print(f'Base model correctly flagged     : {b_rec:.1%}')
print(f'Fine-tuned correctly flagged     : {f_rec:.1%}')
print(f'Improvement                      : {f_rec-b_rec:+.1%}')
print()
print('DOMAIN TERM RECALL')
print(f'  Risk task   — Base: {b_dr:.1%}  FT: {f_dr:.1%}  Δ {f_dr-b_dr:+.1%}')
print(f'  Summary task— Base: {b_sdr:.1%}  FT: {f_sdr:.1%}  Δ {f_sdr-b_sdr:+.1%}')

# ROUGE scores for summaries
try:
    import evaluate as hf_eval
    rouge = hf_eval.load('rouge')
    if base_res['summary']['preds'] and ft_res['summary']['preds']:
        br_r = rouge.compute(predictions=base_res['summary']['preds'], references=base_res['summary']['refs'])
        fr_r = rouge.compute(predictions=ft_res['summary']['preds'],   references=ft_res['summary']['refs'])
        print('ROUGE SCORES')
        for k in ['rouge1','rouge2','rougeL']:
            print(f'  {k}: Base {br_r[k]:.4f}  →  FT {fr_r[k]:.4f}  (Δ {fr_r[k]-br_r[k]:+.4f})')
    else:
        print('No summary examples collected in this run')
except Exception as e:
    print(f'ROUGE skipped: {e}')

"""## 🎬 Step 8 — Three Demo Scenarios: Base vs Fine-Tuned

**These are the cells that win the demo.**  
The contrast between a generic LLM and a domain-tuned model is most visible here.

- **Scenario 1:** Low-risk salaried borrower → expected `Low Risk / Approve`
- **Scenario 2:** High-risk delinquent borrower → expected `High Risk / Reject`  
- **Scenario 3:** Borderline medium-risk case → expected `Medium Risk / Approve with Conditions`
"""

SYSTEM = (
    'You are a Lending Intelligence Assistant at ABC Finance Ltd. '
    'You understand domain concepts: DPD (Days Past Due), FOIR (Fixed Obligation to Income Ratio), '
    'Bureau Score tiers, Collection Buckets, Credit Utilization. '
    'Bureau <650 = High Risk. FOIR >0.60 = financial stress. DPD >60 = serious delinquency. '
    'Provide precise, actionable assessments grounded in these definitions.'
)

def demo(title, question, expected):
    msgs = [
        {'role':'system',    'content': SYSTEM},
        {'role':'user',      'content': question},
    ]
    model.disable_adapter_layers()
    base_ans = infer(model, msgs, max_new=300)
    model.enable_adapter_layers()
    ft_ans   = infer(model, msgs, max_new=300)

    print('='*68)
    print(f'  {title}')
    print(f'  Expected: {expected}')
    print('='*68)
    print(f'\nQUESTION:\n{question[:300]}...')
    print(f'\n{chr(9472)*68}')
    print('  BASE MODEL (no fine-tuning):')
    print(f'{chr(9472)*68}')
    print(base_ans)
    print(f'\n{chr(9472)*68}')
    print('  FINE-TUNED MODEL:')
    print(f'{chr(9472)*68}')
    print(ft_ans)
    print()

print('✅ Demo helper ready')

# SCENARIO 1 — Low-Risk Salaried Borrower
demo(
    title='SCENARIO 1 — Low-Risk Salaried Borrower',
    expected='Low Risk / Approve',
    question=(
        'Classify the credit risk for the following borrower. '
        'Respond with Low Risk, Medium Risk, or High Risk, followed by a detailed justification.\n\n'
        'Borrower Profile:\n'
        '  Age: 35 | Gender: Male | State: Maharashtra\n'
        '  Occupation: Salaried | Monthly Income: ₹75,000\n'
        'Loan Details:\n'
        '  Product: Personal Loan | Sanctioned: ₹4,50,000\n'
        '  EMI: ₹11,200 | Outstanding: ₹2,80,000\n'
        'Credit & Repayment:\n'
        '  Bureau Score: 792 (Very Good, 750-799)\n'
        '  Current DPD: 0 | Max DPD: 0 | Collection Bucket: Current\n'
        '  Default Flag: No | Write-Off Flag: No\n'
        'Derived Metrics:\n'
        '  FOIR: 0.15 (14.9%) | Credit Utilization: 62.2%'
    )
)

# SCENARIO 2 — High-Risk Delinquent Borrower
demo(
    title='SCENARIO 2 — High-Risk Delinquent Borrower',
    expected='High Risk / Reject',
    question=(
        'Provide a loan approval recommendation for this application. '
        'Choose from: Approve, Approve with Conditions, or Reject. Justify your decision.\n\n'
        'Borrower Profile:\n'
        '  Age: 42 | Gender: Male | State: Delhi\n'
        '  Occupation: Self Employed | Monthly Income: ₹42,000\n'
        'Loan Details:\n'
        '  Product: Personal Loan | Sanctioned: ₹3,00,000\n'
        '  EMI: ₹28,560 | Outstanding: ₹2,45,000\n'
        'Credit & Repayment:\n'
        '  Bureau Score: 624 (High Risk, <650)\n'
        '  Current DPD: 75 | Max DPD: 90 | Collection Bucket: 61-90\n'
        '  Default Flag: No | Write-Off Flag: No\n'
        'Derived Metrics:\n'
        '  FOIR: 0.68 (68.0%) | Credit Utilization: 81.7%'
    )
)

# SCENARIO 3 — Borderline Medium-Risk
demo(
    title='SCENARIO 3 — Borderline Medium-Risk',
    expected='Medium Risk / Approve with Conditions',
    question=(
        'Summarise this borrower\'s loan profile for an underwriter review. '
        'Highlight the most significant risk indicators and overall account health.\n\n'
        'Borrower Profile:\n'
        '  Age: 29 | Gender: Female | State: Rajasthan\n'
        '  Occupation: Salaried | Monthly Income: ₹58,000\n'
        'Loan Details:\n'
        '  Product: Vehicle Loan | Sanctioned: ₹5,00,000\n'
        '  EMI: ₹13,200 | Outstanding: ₹3,90,000\n'
        'Credit & Repayment:\n'
        '  Bureau Score: 712 (Good, 700-749)\n'
        '  Current DPD: 0 | Max DPD: 45 | Collection Bucket: Current\n'
        '  Default Flag: No | Write-Off Flag: No\n'
        'Derived Metrics:\n'
        '  FOIR: 0.51 (51.0%) | Credit Utilization: 78.0%'
    )
)

"""## 💾 Step 9 — Save Report & Download Everything"""

# Build and save evaluation report
report = '\n'.join([
    '# Lending AI SLM — Evaluation Report',
    '',
    '## Credit Risk Classification',
    '| Metric | Base Model | Fine-Tuned | Delta |',
    '|--------|-----------|------------|-------|',
    f'| Accuracy | {ba:.1%} | {fa:.1%} | {fa-ba:+.1%} |',
    f'| F1 Macro | {bf:.4f} | {ff:.4f} | {ff-bf:+.4f} |',
    '',
    '**Per-class F1:**',
    '| Class | Base F1 | FT F1 | Base Recall | FT Recall |',
    '|-------|---------|-------|-------------|-----------|',
] + [
    f'| {cls} | {br.get(cls,{}).get("f1-score",0):.3f} | {fr.get(cls,{}).get("f1-score",0):.3f} | {br.get(cls,{}).get("recall",0):.3f} | {fr.get(cls,{}).get("recall",0):.3f} |'
    for cls in RISK_LABELS
] + [
    '',
    '## Loan Approval Recommendation',
    '| Metric | Base Model | Fine-Tuned | Delta |',
    '|--------|-----------|------------|-------|',
    f'| Accuracy | {baa:.1%} | {faa:.1%} | {faa-baa:+.1%} |',
    f'| F1 Macro | {baf:.4f} | {faf:.4f} | {faf-baf:+.4f} |',
    '',
    '## Business Impact',
    f'- High Risk Recall — Base: {b_rec:.1%} → Fine-Tuned: {f_rec:.1%} (Δ {f_rec-b_rec:+.1%})',
    f'- Domain Term Recall (Risk) — Base: {b_dr:.1%} → FT: {f_dr:.1%}',
    f'- Domain Term Recall (Summary) — Base: {b_sdr:.1%} → FT: {f_sdr:.1%}',
    '',
    '## Interpretation',
    'High Risk recall improvement means more problematic borrowers are correctly',
    'flagged for collections intervention before they default.',
    'Domain Term Recall improvement shows the fine-tuned model uses lending',
    'terminology (DPD, FOIR, Bureau Score tiers) correctly and consistently.',
])

with open('outputs/evaluation_report.md', 'w') as f:
    f.write(report)

eval_data = {
    'risk_accuracy_base': ba,       'risk_accuracy_ft': fa,
    'risk_f1_macro_base': bf,        'risk_f1_macro_ft': ff,
    'approval_accuracy_base': baa,   'approval_accuracy_ft': faa,
    'approval_f1_macro_base': baf,   'approval_f1_macro_ft': faf,
    'high_risk_recall_base': b_rec,  'high_risk_recall_ft': f_rec,
    'domain_recall_risk_base': b_dr, 'domain_recall_risk_ft': f_dr,
    'domain_recall_sum_base': b_sdr, 'domain_recall_sum_ft': f_sdr,
}
with open('outputs/evaluation_results.json', 'w') as f:
    json.dump(eval_data, f, indent=2)

print('✅ evaluation_report.md saved')
print('✅ evaluation_results.json saved')

import shutil
from google.colab import files

# Zip adapter weights separately (largest file)
shutil.make_archive('adapter_weights', 'zip', 'outputs/adapter')

# Zip all outputs (reports, metrics, loss curve)
shutil.make_archive('all_outputs', 'zip', 'outputs')

print('Downloading files...')
files.download('adapter_weights.zip')            # LoRA weights (~60 MB)
files.download('outputs/evaluation_report.md')   # Human-readable report
files.download('outputs/evaluation_results.json') # Structured metrics
files.download('outputs/training_metrics.json')   # Training stats
files.download('outputs/training_loss.png')       # Loss curve
files.download('all_outputs.zip')                 # Everything
print('✅ All files downloaded')

"""## 📤 Step 10 — Push Results to GitHub

**Before running:** Create a GitHub Personal Access Token (PAT):  
→ github.com → Settings → Developer Settings → Personal Access Tokens → Tokens (classic) → New  
→ Scope: `repo` → Generate → paste below

"""

GITHUB_USERNAME = 'anmolvarshney77'
GITHUB_PAT      = 'YOUR_GITHUB_PAT_HERE'   # <-- paste your GitHub PAT here
REPO            = 'SLM-Lending-and-Credit'

!git config user.email 'anmol@lyzr.ai'
!git config user.name  'Anmol Varshney'

# Stage all generated artifacts
!git add data/processed/
!git add outputs/evaluation_report.md outputs/evaluation_results.json outputs/training_metrics.json
!git add -f outputs/training_loss.png   # force-add (might be gitignored)

!git status
!git commit -m 'Add JSONL datasets, training metrics, and evaluation report'

remote = f'https://{GITHUB_USERNAME}:{GITHUB_PAT}@github.com/{GITHUB_USERNAME}/{REPO}.git'
!git remote set-url origin {remote}
!git push origin main

print('✅ Pushed to GitHub')
print(f'Repo: https://github.com/{GITHUB_USERNAME}/{REPO}')

"""---

## ✅ Submission Checklist

| Item | Status |
|------|--------|
| `data/processed/train.jsonl` — 2,400 training examples | ✅ |
| `data/processed/val.jsonl` — 300 validation examples | ✅ |
| `data/processed/test.jsonl` — 300 held-out test examples | ✅ |
| `outputs/adapter/` — LoRA adapter weights | ✅ |
| `outputs/training_metrics.json` — loss + timing | ✅ |
| `outputs/training_loss.png` — loss curve chart | ✅ |
| `outputs/evaluation_report.md` — before-vs-after comparison | ✅ |
| `outputs/evaluation_results.json` — structured metrics | ✅ |
| `notebooks/01_data_preparation.ipynb` | ✅ |
| `notebooks/02_fine_tuning.ipynb` | ✅ |
| `notebooks/03_evaluation.ipynb` | ✅ |
| `README.md` | ✅ |

**Final steps before deadline:**
1. Add `azentio-talent-Aquisition` as a GitHub collaborator: repo → Settings → Collaborators → Add
2. Email repo URL to **tateam@azentio.com**

"""